version: '3'

services:
  dynamodb:
    build: ./common/local-env/dynamodb-local
    ports:
      - "8000:8000"
  rabbitmq:
    build: ./common/local-env/rabbit/
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: "localhost"
